- name:  Base Installation and Server Hardening
  hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    mysql_root_password: fart
  gather_facts: yes
  become: true
  roles:
    - sshd
    - common
    - mysql
    - ufw
    - backup1-restore
  tags:
    - sshd
    - common
    - mysql
    - ufw
    - backup1-restore